FROM eclipse-temurin:21-jre-alpine

RUN mkdir -p /deployments \
    && chown 1000:1000 /deployments

COPY --chown=1000:1000 build/quarkus-app/lib/ /deployments/lib/
COPY --chown=1000:1000 build/quarkus-app/*.jar /deployments/
COPY --chown=1000:1000 build/quarkus-app/app/ /deployments/app/
COPY --chown=1000:1000 build/quarkus-app/quarkus/ /deployments/quarkus/

USER 1000
EXPOSE 8090
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

CMD ["java", "-jar", "/deployments/quarkus-run.jar"]
